language: python
python:
  - "2.7"
  
# command to install dependencies
install:
  - pip install numpy
  - pip install matplotlib
  - pip install ScientificPython
# command to run tests
script: make testwithdatadownload
