#dist: trusty

matrix:
  include:
  
  # Ubuntu Trusty 14.04 Docker container build and test
  - services:
      - docker
    language: cpp
    install:
      - docker build -t shingle .
    script:
      - docker run -a stdout -t shingle make unittest
      - docker run -v $PWD:/run -w="/run" -a stdout -t shingle shingle -t

  # Ubuntu Trusty 14.04 Travis apt base packages build and test
  - language: python
    python: 2.7
    sudo: required
    compiler: gcc
    addons:
      apt:
        packages:
          # - git
          # - gcc
          # - g++
          - build-essential
          - python-setuptools
          - python-dev
          - python-pip
          - python-scipy
          - python-numpy
          - python-scientific
          - python-matplotlib 
          - python-shapely
          - python-pyproj
          - python-pil
          - gmsh
          - python-pytest
    virtualenv:
      system_site_packages: true
    install:
      - pip install Pydap
    before_script:
      - export LD_LIBRARY_PATH="$HOME/build/shingleproject/Shingle/lib/:$LD_LIBRARY_PATH"
      - export LIBRARY_PATH="$HOME/build/shingleproject/Shingle/lib/:$LIBRARY_PATH"
    script:
      - make
      - make unittest
      - make test

  # Ubuntu Trusty 14.04 Travis pip base packages build and test
  - language: python
    python: 2.7
    sudo: required
    compiler: gcc
    addons:
      apt:
        packages:
          - gmsh
    virtualenv:
      system_site_packages: true
    install:
      - pip install numpy Scientific matplotlib pyproj Pydap shapely Pillow pytest
    before_script:
      - export LD_LIBRARY_PATH="$HOME/build/shingleproject/Shingle/lib/:$LD_LIBRARY_PATH"
      - export LIBRARY_PATH="$HOME/build/shingleproject/Shingle/lib/:$LIBRARY_PATH"
    script:
      - make
      - make unittest
      - make test



