# Ubuntu Trusty 14.04 Travis apt base packages build and test
env:
  - NAME=trusty-apt
dist: trusty
language: python
python: 2.7
sudo: required
compiler: gcc
addons:
  apt:
    packages:
      # - git
      # - gcc
      # - g++
      - build-essential
      - python-setuptools
      - python-dev
      - python-pip
      - python-scipy
      - python-numpy
      - python-scientific
      - python-matplotlib 
      - python-shapely
      - python-pyproj
      - python-pil
      - gmsh
      - python-pytest
      - curl
virtualenv:
  system_site_packages: true
install:
  # Temporarily update all apt packages
  - sudo apt-get update
  - sudo apt-get install -y git gcc g++ build-essential python-setuptools python-dev python-pip python-scipy python-numpy python-scientific python-matplotlib python-shapely python-pyproj python-pil gmsh python-pytest
  - pip install Pydap
before_script:
  - export LD_LIBRARY_PATH="$HOME/build/shingleproject/Shingle/lib/:$LD_LIBRARY_PATH"
  - export LIBRARY_PATH="$HOME/build/shingleproject/Shingle/lib/:$LIBRARY_PATH"
  - export LD_LIBRARY_PATH="/usr/lib/python2.7/dist-packages/Scientific/:$LD_LIBRARY_PATH"
  - export LIBRARY_PATH="/usr/lib/python2.7/dist-packages/Scientific/:$LIBRARY_PATH"
  - export PYTHONPATH="/usr/lib/python2.7/dist-packages/Scientific/:$PYTHONPATH"
script:
  - make
  - make unittest
  # Pre-download, to best work with Travis timeout
  - curl http://store.pangaea.de/Publications/TimmermannR_et_al_2010/RTopo105b_50S.nc -o test/Amundsen_Sea/data/RTopo.nc
  #- make test
  - ./bin/shingle -t ./test/UK_NorthSea_gebco2014_opendap/UK_NorthSea_gebco2014_opendap.brml
