language: python
python:
  - "2.7"
sudo: required
#install: "pip install -r requirements.txt"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y -qq python-numpy python-scientific python-matplotlib
install: "pip install numpy matplotlib shapely pygdal Pillow"
script: make test
