dist: trusty

matrix:
  include:
  - language: python
    python: "2.7"
    sudo: required
    addons:
      apt:
        packages:
          - python-numpy
          - python-scientific
          - python-matplotlib
          - gcc
          - g++
          - gfortran
          - tree
    virtualenv:
      system_site_packages: true
    install:
      - pip install numpy matplotlib pyproj Pydap shapely Pillow
    before_script:
      - sudo apt-get install -qq python-numpy python-scientific python-matplotlib gmsh
      - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$HOME/build/shingleproject/Shingle/lib/:$HOME/build/shingleproject/Shingle/lib/spud/:$HOME/build/shingleproject/Shingle/spud/.libs/:$HOME/build/lib.linux-x86_64-2.7/"
      - export LIBRARY_PATH="$LIBRARY_PATH:$HOME/build/shingleproject/Shingle/lib/:$HOME/build/shingleproject/Shingle/spud/:$HOME/build/shingleproject/Shingle/spud/.libs/:$HOME/build/lib.linux-x86_64-2.7/"
    script:
      - pip install numpy matplotlib pyproj Pydap shapely Pillow pytest
      - python -c 'import Scientific.IO'
      - ./configure
      - make
      - make unittest
      - make test

  - services:
      - docker
    language: cpp
    install:
      - docker build -t shingle .
    script:
      - docker run -a stdout -t shingle make unittest
      - docker run -v $PWD:/run -w="/run" -a stdout -t shingle shingle -t



